version: '3.7'

services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
     - '8081:80'
   
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
     - '44390:80'



